<!DOCTYPE html>
<!--[if IE 8]>
<html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]>
<html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en"> <!--<![endif]-->
<head>
    <title>Boubacar Diallo</title>
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="developpement et integration web">
    <meta name="author" content="Boubacar diallo">
  
    <link rel="shortcut icon" href="favicon.ico">
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,300italic,400italic' rel='stylesheet'
          type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <!-- Global CSS -->
    <link rel="stylesheet" href="assets/plugins/bootstrap/css/bootstrap.min.css">
    <!-- Plugins CSS -->
    <link rel="stylesheet" href="assets/plugins/font-awesome/css/font-awesome.css">




    <!-- Theme CSS -->
    <link id="theme-style" rel="stylesheet" href="assets/css/styles.css">
    <link rel="stylesheet" href="assets/css/lightbox.css">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->


</head>
<style type="text/css">

</style>

<body>
<!-- ******HEADER****** -->
<header class="header">
    <div class="container">
        <img class="profile-image img-responsive pull-left img-circle " src="assets/images/ovu.png"
             alt="Boubacar diallo"/>

        <div class="profile-content pull-left">
            <h1 class="name">Boubacar Diallo</h1>

            <h2 class="desc">Développeur et Intégrateur web</h2>
            <ul class="social list-inline">
                <li><a href="https://twitter.com/ovutros?lang=fr"><i class="fa fa-twitter"></i></a></li>
                <li><a href="https://plus.google.com/u/0/114112974646553261117/posts"><i class="fa fa-google-plus"></i></a></li>
               
                <li><a href="https://github.com/Bdiallo16"><i class="fa fa-github-alt"></i></a></li>

            </ul>

        </div>
        <!--//profile-->
       

        <a class="btn btn-cta-primary pull-right" href="#" ><i class="fa fa-paper-plane"></i> Contact</a>
    </div>
    <!--//container-->


</header>
<!--//header-->


<div class="container sections-wrapper">
<div class="row">
<div class="primary col-md-8 col-sm-12 col-xs-12">
    <section class="about section">
        <div class="section-inner">
            <h2 class="heading">A propos</h2>

            <div class="content">
                <p>Developpeur Intégrateur et passionné du web, Je dispose de quelques expériences  dans le domaine développement d’application  web et mobiles par le biais de mes stages et projets  réalisés au cours de ma formation universitaire. </p>

                <p></p>

            </div>
            <!--//content-->
        </div>
        <!--//section-inner-->
    </section>
    <!--//section-->
   
    <section class="latest section">
        <div class="section-inner">

            <div class="content">
                <h2 class="heading">Quelques travaux</h2>

                <div class="item row">
                <a class="col-md-4 col-sm-4 col-xs-12" href="assets/images/projects/destock.png"
                   data-lightbox="netmultimedias" data-toggle="lightbox" data-title="destockage discount">
                    <img class="img-responsive project-image" src="assets/images/projects/destock.png"
                         alt="destockage discount"/>
                </a>

                <div class="desc col-md-8 col-sm-8 col-xs-12">
                    <h4 class="university"><span class="year">2015(un mois)</span>:Développeur intégrateur - <span
                            class="place"><a href="http://www.netmultimedias.com/">Netmulimedias</a></span></h4>


                    <p>-Intégration et référencement  sous Prestashop .</p>
                    <p>-Analyse et suivi des performances</p>
                    <p>-Intégration du tracking et suivi du plan de taggage (google analytics et google webmasters tools)</p>
                    
                </div>
                <!--//desc-->
                </div>
                <!--//item-->
                <div class="item row">
                    <a class="col-md-4 col-sm-4 col-xs-12" href="assets/images/projects/be2.png"
                       data-lightbox="be2" data-toggle="lightbox" data-title="Gestion de cours, devoirs, notes....">
                        <img class="img-responsive project-image" src="assets/images/projects/be2.png"
                             alt="destockage discount"/>
                    </a>

                    <div class="desc col-md-8 col-sm-8 col-xs-12">
                        <h4 class="university"><span class="year">2014 (6mois de stage)</span>:Développeur intégrateur  </span><span class="place"><a href="http://sfa.univ-poitiers.fr/licence-professionnelle-sciences-technologies-sante-mention-systemes-informatiques-et-logiciels-specialite-technologies-logicielles-pour-le-web-et-les-terminaux-mobiles-20405.kjsp?RH=1268644504943">-Sp2mi</a></span></h4>


                        <p>-Développement d'une application de gestion des notes dévoirs des étudiants, et salles de l'université .</p>
                        <p>-Modélisation UML de l'application</p>
                        <p>-Développement  d'un plugin Zotero permettatnt de faire une gestion  des références bibliographiques </p>
                        <p>-Documentation technique destinée aux futurs utilisateurs</p>
                        
                    </div>
                    <!--//desc-->
                </div>
                <!--//item-->
                <div class="item row">
                    <a class="col-md-4 col-sm-4 col-xs-12" href="assets/images/projects/scientibus.png"
                       src="assets/images/projects/scientibus.png" data-lightbox="scientibus" data-toggle="lightbox" data-title="scientibus">
                        <img class="img-responsive project-image" src="assets/images/projects/scientibus.png"
                             alt="scientibus"/>
                    </a>

                    <div class="desc col-md-8 col-sm-8 col-xs-12">
                        <h4 class="university">  <span class="year">2012(3mois de stage)</span>:Webmaster developpeur<span class="place">
                        <a href="http://www.unilim.fr/scientibus/"> -Xlim Limoges </a></span>
                        </h4>

                        <p>Refonte d’un site internet :</p>
                        <p> -Analyse de l’existant pour répertorier les fonctionnalités obsolètes</p>
                            <p>-Modélisation objet de l’application  </p>
                            <p>- Développement php/Mysql pour la partie backoffice et intégration HTML5/CSS3 sous Wordpress  pour la partie front office.</p>

                        
                    </div>
                    <!--//desc-->
                </div>
                <!--//item-->

                <div class="item row">
                    <a class="col-md-4 col-sm-4 col-xs-12" href="assets/images/projects/mangily.png"
                       data-lightbox="mangily" data-toggle="lightbox" data-title="mangily hotel">
                        <img class="img-responsive project-image" src="assets/images/projects/mangily.png"
                             alt="mangily hotel"/>
                    </a>

                    <div class="desc col-md-8 col-sm-8 col-xs-12">
                        <h4 class="university"><span class="year">2010(1 mois de stage)</span>:Webmaster intégrateur <span class="place"><a href="http://www.vizioncommunication.com">-vizion communication</a></span> </h4>

                        <p>Intégration HTML,CSS, participation au  développement d’un module de promotion et mise en place un slider .</p>

                       
                    </div>
                    <!--//desc-->
                </div>
               
                <!--//item-->
                
                                <h3 class="university"><a class="more-link" href="https://github.com/Bdiallo16" target="_blank"><i class="fa fa-external-link"></i> Plus d'infos</a></h3>
                                
                            

            </div>
            <!--//content-->
        </div>
        <!--//section-inner-->
    </section>
    <!--//section-->


</div>
<!--//primary-->
<div class="secondary col-md-4 col-sm-12 col-xs-12">
<aside class="info aside section">
    <div class="section-inner">
        <h2 class="heading">Coordonnées</h2>

        <div class="content">
            <ul class="list-unstyled">
                <li><i class="fa fa-map-marker"></i><span class="sr-only">Location:</span> Choisy-Le-Roi, France</li>
                <li><i class="fa fa-envelope-o"></i><span class="sr-only">Email:</span><a href="#">boubacar.diallo16@gmail.com</a>
                </li>
                <li><i class="fa fa-link"></i><span class="sr-only">Website:</span><a href="#">http://www.bouba-diallo.fr</a>
                </li>
            </ul>
        </div>
        <!--//content-->
    </div>
    <!--//section-inner-->
</aside>
<!--//aside-->

<aside class="skills aside section">
<div class="section-inner">
<h2 class="heading">Compétences</h2>

<div class="content">


<div class="skillset">
<div class="item">
    <h3 class="level-title">HTML5 &amp; CSS3<span class="level-label">avancées</span></h3>

    <div class="level-bar">
        <div class="level-bar-inner" data-level="80%">
        </div>
    </div>
    <!--//level-bar-->
</div>
<!--//item-->
<div class="item">
    <h3 class="level-title">PHP<span class="level-label" data-toggle="tooltip" data-placement="left"
                                     data-animation="true"
                                     title="You can use the tooltip to add more info...">intermediaire</span>
    </h3>

    <div class="level-bar">
        <div class="level-bar-inner" data-level="60%">
        </div>
    </div>
    <!--//level-bar-->
</div>
<!--//item-->

<div class="item">
    <h3 class="level-title">Javascript &amp; jQuery<span class="level-label">intermediaire</span></h3>

    <div class="level-bar">
        <div class="level-bar-inner" data-level="60%">
        </div>
    </div>
    <!--//level-bar-->
</div>
<!--//item-->

<div class="item">
    <h3 class="level-title">Symfony<span class="level-label">débutant</span></h3>

    <div class="level-bar">
        <div class="level-bar-inner" data-level="45%">
        </div>
    </div>
    <!--//level-bar-->
</div>
<!--//item-->

<!--//item-->
<div class="container">

    <!-- Trigger the modal with a button -->
    <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Autres
        compétences
    </button>

    <!-- Modal -->
    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Autres compétences</h4>
                </div>
                <div class="modal-body">
                    <p>

                    <div class="item">
                        <h3 class="level-title">Prestashop<span class="level-label">intermédiaire</span></h3>

                        <div class="level-bar">
                            <div class="level-bar-inner" data-level="60%">
                            </div>
                        </div>
                        <!--//level-bar-->
                    </div>
                    <!--//item-->
                    
                    <div class="item">
                        <h3 class="level-title">Drupal<span class="level-label">intermediaire</span></h3>

                        <div class="level-bar">
                            <div class="level-bar-inner" data-level="60%">
                            </div>
                        </div>
                        <!--//level-bar-->
                    </div>
                    <!--//item-->
                    <div class="item">
                        <h3 class="level-title">Seo<span class="level-label">avancées</span></h3>

                        <div class="level-bar">
                            <div class="level-bar-inner" data-level="70%">
                            </div>
                        </div>
                        <!--//level-bar-->
                    </div>
                    <!--//item-->
                    <div class="item">
                        <h3 class="level-title">Responsive design<span class="level-label">intermediaire</span></h3>

                        <div class="level-bar">
                            <div class="level-bar-inner" data-level="60%">
                            </div>
                        </div>
                        <!--//level-bar-->
                    </div>
                    <!--//item-->
                    <div class="item">
                        <h3 class="level-title">Graphisme<span class="level-label">débutant</span></h3>

                        <div class="level-bar">
                            <div class="level-bar-inner" data-level="45%">
                            </div>
                        </div>
                        <!--//level-bar-->
                    </div>
                    <!--//item-->
                   


                   </p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
                </div>
            </div>

        </div>
    </div>

</div>


</div>
</div>
<!--//content-->
</div>
<!--//section-inner-->
</aside>
<!--//section-->
<aside class="education aside section">
    <div class="section-inner">
        <h2 class="heading">Formations</h2>

        <div class="content">
        <div class="item">
                <h3 class="title"><i class="fa fa-graduation-cap"></i> Développeur intégrateur Web
                    </h3>
                <h4 class="university">Ecole 3W academy Paris(18) <span class="year"></span></h4>
            </div>
            <div class="item">
                <h3 class="title"><i class="fa fa-graduation-cap"></i> Licence professionnelle technologies logicielles
                    pour le web et les terminaux mobiles </h3>
                <h4 class="university">Université de Poitiers <span class="year"></span></h4>
            </div>
            <!--//item-->
            <div class="item">
                <h3 class="title"><i class="fa fa-graduation-cap"></i> DUT Webmaster et Gestionnaire d’Intranet </h3>
                <h4 class="university">Université de Limoges <span class="year"></span></h4>
            </div>
            <!--//item-->
        </div>
        <!--//content-->
    </div>
    <!--//section-inner-->
</aside>
<!--//section-->

<aside class="languages aside section">
    <div class="section-inner">
        <h2 class="heading">Langues étrangeres</h2>

        <div class="content">
            <ul class="list-unstyled">
                <li class="item">
                    <span class="title"><strong>Anglais:</strong></span>
                    <span class="level"> <br class="visible-xs"/><i class="fa fa-star"></i> <i class="fa fa-star"></i>  <i
                            class="fa fa-star"></i> <i
                            class="glyphicon glyphicon-star-empty"></i><i
                            class="glyphicon glyphicon-star-empty"></i></span>
                </li>
                <!--//item-->

            </ul>
        </div>
        <!--//content-->
    </div>
    <!--//section-inner-->
</aside>
<!--//section-->

<aside class="blog aside section">
    <div class="section-inner">
        <h2 class="heading">Liens utiles</h2>

        <p> <a href="https://secure.php.net/manual/fr/" target="_blank">Apprendre php </a></p>

        <p> <a href="http://api.jquery.com/" target="_blank">JQuery </a></p>

        <p> <a href="http://symfony.com/doc/current/index.html" target="_blank">Symfony </a></p>

        <p> <a href="https://www.w3schools.com/" target="_blank">Html/Css </a></p>

    </div>
    <!--//section-inner-->
</aside>
<!--//section-->


</div>
<!--//secondary-->
</div>
<!--//row-->
</div>
<!--//masonry-->

<!-- ******FOOTER****** -->
<footer class="footer">
    <div class="container text-center">
        <small class="copyright"> Boubacar Diallo</small>
        <ul class="social list-inline">
                <li><a href="https://twitter.com/ovutros?lang=fr"><i class="fa fa-twitter"></i></a></li>
                <li><a href="https://plus.google.com/u/0/114112974646553261117/posts"><i class="fa fa-google-plus"></i></a></li>
               
                <li><a href="https://github.com/Bdiallo16"><i class="fa fa-github-alt"></i></a></li>

            </ul>
    </div>
    <!--//container-->
</footer>
<!--//footer-->
</div>
<!-- Javascript -->
<script type="text/javascript" src="assets/plugins/jquery-1.11.2.min.js"></script>
<script type="text/javascript" src="assets/plugins/jquery-migrate-1.2.1.min.js"></script>
<script type="text/javascript" src="assets/plugins/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="assets/plugins/jquery-rss/dist/jquery.rss.min.js"></script>


<!-- custom js -->
<script type="text/javascript" src="assets/js/main.js"></script>
<script type="text/javascript" src="assets/js/app.js"></script>
<script type="text/javascript" src="assets/js/lightbox.min.js"></script>

<script>
    $(document).delegate('*[data-toggle="lightbox"]', 'click', function (event) {
        event.preventDefault();
        $(this).ekkoLightbox();
    });

</script>
<script>document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>')</script>

</body>
</html> 

